name: cng-forum-workshop
channels:
  - conda-forge
dependencies:
  - dask
  - jupyter-server-proxy
  - fsspec
  - icechunk
  - matplotlib
  - nbgitpuller
  - netcdf4
  - numpy
  - obstore
  - pandas
  - pystac
  - rasterio
  - rustac
  - scipy
  - virtualizarr
  - xarray
  - pip
  - pip:
    - cloudgeometer